### PR TITLE
Update cython to version 0.29.32

### PR DESCRIPTION
**Pull request by jameshilliard**
The current cython generated code fails to build on version 3.11.

Fixes:
```c
wsaccel/utf8validator.c:196:12: fatal error: longintrepr.h: No such file or directory
  196 |   #include "longintrepr.h"
      |            ^~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by jameshilliard** [comment]
FYI I noticed in the readme it says that:
> AutobahnPython and ws4py are not actively maintained.

This is incorrect as [autobahn-python](https://github.com/crossbario/autobahn-python) is actively maintained and [still uses this module](https://github.com/crossbario/autobahn-python/blob/v22.7.1/autobahn/websocket/utf8validator.py#L58) in the latest release.

**Comment by jameshilliard** [comment]
@methane think you could spin a new release with this?
